// @mandhira/db — generated database types, Zod validation schemas, Supabase clients.
//
// Table types are NEVER hand-written (TRD §1.4): `types.ts` is generated by
// `pnpm db:types` from the local Supabase schema, and CI fails if it is stale.
// The Zod schemas here are hand-written on purpose — they carry product rules the
// database cannot express as readable errors, and they are pinned to the generated
// types by `schemas.test.ts`.

export type { Database, Json } from "../types";
// The generated enum value arrays, so a UI that offers a choice cannot drift from what the
// database will accept.
export { Constants } from "../types";
export * from "./types-helpers";
export * from "./critical-fields";
export * from "./schemas/primitives";
export * from "./schemas/place";
export * from "./schemas/experience";
export * from "./schemas/journey";

// `rate-limit` is a subpath too: it needs a service-role client, and nothing that reaches
// a browser bundle should be able to import it by accident.

// Clients are exported from subpaths (`@mandhira/db/client/browser`, `/server`, …) rather
// than here, so that importing a Zod schema never pulls a server-only module — and in
// particular never pulls the service-role client — into a client bundle.
