// @mandhira/db — generated database types + Zod validation schemas.
//
// Table types are NEVER hand-written (TRD §1.4): `types.ts` is generated by
// `pnpm db:types` from the local Supabase schema, and CI fails if it is stale.
// The Zod schemas here are hand-written on purpose — they carry product rules the
// database cannot express as readable errors, and they are pinned to the generated
// types by `schemas.test.ts`.

export type { Database, Json } from "../types";
export * from "./types-helpers";
export * from "./schemas/primitives";
export * from "./schemas/place";
export * from "./schemas/experience";
export * from "./schemas/journey";
