#!/usr/bin/env node
/**
 * Generates the traveler app's locale list from the `locales` table (PRD-LANG-002).
 *
 * A language becomes available by being a row in Ops (D-028) — but next-intl needs the list
 * at build time to route `/[locale]/…`, so the row is turned into code here and committed.
 * Adding a language is then: add the row in Ops, run `pnpm i18n:locales`, deploy. No hand
 * edits to the front end, which is what PRD-LANG-002 asks for.
 *
 * Reads through PostgREST with the anon key: `locales` is one of the four tables anon may
 * read (0031), so this needs no secret beyond what the browser already carries.
 *
 * `--check` writes nothing and exits 1 when the committed file is out of date, for CI.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TARGET = join(ROOT, "packages/i18n/src/locales.generated.ts");
const CHECK = process.argv.includes("--check");

function env(name) {
  if (process.env[name]) return process.env[name];

  // Fall back to .env.local, which is where these live in development.
  for (const file of [".env.local", ".env"]) {
    try {
      const text = readFileSync(join(ROOT, file), "utf8");
      const match = new RegExp(`^${name}=(.*)$`, "m").exec(text);
      if (match?.[1]) return match[1].trim();
    } catch {
      // No such file; try the next one.
    }
  }
  return undefined;
}

const url = env("NEXT_PUBLIC_SUPABASE_URL");
const key = env("NEXT_PUBLIC_SUPABASE_ANON_KEY");

if (!url || !key) {
  console.error(
    "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY (or put them in .env.local).",
  );
  process.exit(1);
}

const response = await fetch(
  `${url}/rest/v1/locales?select=code,name_native,name_en,sort_order&is_active=eq.true&order=sort_order,code`,
  { headers: { apikey: key, authorization: `Bearer ${key}` } },
);

if (!response.ok) {
  console.error(`Could not read locales: ${response.status} ${await response.text()}`);
  process.exit(1);
}

const rows = await response.json();
if (!Array.isArray(rows) || rows.length === 0) {
  console.error("No active locales. The app needs at least English.");
  process.exit(1);
}

// English first: it is the default and every fallback ends there (TRD §1.4).
const ordered = [...rows].sort((a, b) => (a.code === "en" ? -1 : b.code === "en" ? 1 : 0));

if (!ordered.some((locale) => locale.code === "en")) {
  console.error("English is not active. Every fallback ends there, so it cannot be switched off.");
  process.exit(1);
}

// Prettier drops the quotes from a key that does not need them, so the generator writes the
// style Prettier would: otherwise `--check` here and `format:check` would each undo the other.
const keyOf = (code) => (/^[a-z][a-z0-9]*$/.test(code) ? code : JSON.stringify(code));

const codes = ordered.map((locale) => JSON.stringify(locale.code));
const oneLine = `[${codes.join(", ")}] as const`;
const list =
  `export const GENERATED_LOCALES = ${oneLine};`.length <= 100
    ? oneLine
    : `[\n${codes.map((code) => `  ${code},`).join("\n")}\n] as const`;

const labels = ordered
  .map((locale) => `  ${keyOf(locale.code)}: ${JSON.stringify(locale.name_native)},`)
  .join("\n");

const file = `// Generated by \`pnpm i18n:locales\` from the \`locales\` table. Do not edit by hand.
//
// A language is added in Ops (O18) and appears here after this script runs: next-intl needs the
// list at build time to route \`/[locale]/…\` (PRD-LANG-002, D-210).

export const GENERATED_LOCALES = ${list};

/** Each language named in its own script, as an operator entered it. */
export const GENERATED_LOCALE_LABELS = {
${labels}
} as const;
`;

const current = (() => {
  try {
    return readFileSync(TARGET, "utf8");
  } catch {
    return "";
  }
})();

if (current === file) {
  console.log(`locales are current: ${ordered.map((locale) => locale.code).join(", ")}`);
  process.exit(0);
}

if (CHECK) {
  console.error("The locale list is out of date. Run `pnpm i18n:locales` and commit the result.");
  process.exit(1);
}

writeFileSync(TARGET, file);
console.log(`wrote ${ordered.length} locales: ${ordered.map((locale) => locale.code).join(", ")}`);
