import nextPlugin from "@next/eslint-plugin-next";
import tseslint from "typescript-eslint";
import base from "./base.js";

/** Flat config for Next.js apps: base + next core-web-vitals + Mandhira boundaries. */
export default tseslint.config(
  ...base,
  // next-env.d.ts is generated by Next on every build and is gitignored.
  { ignores: ["next-env.d.ts"] },
  {
    plugins: { "@next/next": nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
    },
  },
  {
    // CLAUDE.md §4: vendor SDKs only inside packages/providers; journey logic only in the engine.
    files: ["app/**/*.{ts,tsx}", "components/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@ai-sdk/*", "ai", "resend", "web-push", "openrouteservice-js"],
              message: "Vendor SDKs may only be imported inside packages/providers.",
            },
          ],
        },
      ],
    },
  },
);
