import nextPlugin from "@next/eslint-plugin-next";
import tseslint from "typescript-eslint";
import base from "./base.js";

/**
 * Flat config for Next.js apps: base (which already carries the vendor-SDK boundary) plus
 * Next's core-web-vitals rules.
 */
export default tseslint.config(
  ...base,
  // next-env.d.ts is generated by Next on every build and is gitignored.
  { ignores: ["next-env.d.ts"] },
  {
    plugins: { "@next/next": nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
    },
  },
);
