// Generated by `pnpm i18n:locales` from the `locales` table. Do not edit by hand.
//
// A language is added in Ops (O18) and appears here after this script runs: next-intl needs the
// list at build time to route `/[locale]/…` (PRD-LANG-002, D-210).

export const GENERATED_LOCALES = ["en", "te", "hi"] as const;

/** Each language named in its own script, as an operator entered it. */
export const GENERATED_LOCALE_LABELS = {
  en: "English",
  te: "తెలుగు",
  hi: "हिन्दी",
} as const;
